# -*- coding: utf-8 -*-
"""Naive bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N2vJIek_i8AT8mahr_Omn0ZiBN8Wpdz1
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

d=pd.read_csv('diabetes.csv')

d.describe()

d.info()

d.head()

b=d.corr()
sns.heatmap(b, annot=True)
plt.show()

X=d.iloc[:,[1,2,3,5]].values
y=d.iloc[:,-1].values

y

from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

y_pred = classifier.predict(X_train)

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_train, y_pred))

